### PR TITLE
Enable Windows build

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
```
     Creating library build\temp.win-amd64-cpython-38\Release\src\flint\types\nmod.cp38-win_amd64.lib and object build\temp.win-amd64-cpython-38\Release\src\flint\types\nmod.cp38-win_amd64.exp
  nmod.obj : error LNK2001: unresolved external symbol __flint_clz_tab
  build\lib.win-amd64-cpython-38\flint\types\nmod.cp38-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
  error: Command "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\bld\python-flint_1724819685511\_h_env\lib /LIBPATH:C:\ /LIBPATH:D:\bld\python-flint_1724819685511\_h_env\libs /LIBPATH:C:\Miniforge\Library\lib /LIBPATH:D:\bld\python-flint_1724819685511\_h_env\libs /LIBPATH:D:\bld\python-flint_1724819685511\_h_env /LIBPATH:D:\bld\python-flint_1724819685511\_h_env\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64 /LIBPATH:D:\bld\python-flint_1724819685511\_h_env\Library\lib /LIBPATH:D:\bld\python-flint_1724819685511\_h_env\Library\lib flint.lib mpir.lib mpfr.lib pthreads.lib /EXPORT:PyInit_nmod build\temp.win-amd64-cpython-38\Release\src\flint\types\nmod.obj /OUT:build\lib.win-amd64-cpython-38\flint\types\nmod.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-38\Release\src\flint\types\nmod.cp38-win_amd64.lib" failed with exit status 1120
  error: subprocess-exited-with-error
  
  Building wheel for python-flint (pyproject.toml) did not run successfully.
  exit code: 1
```

**Comment by oscarbenjamin** [comment]
Thanks for opening this.

I don't understand how to interpret the build scripts in a feedstock repo which means I never really understand what these PRs are doing. I am assuming that both Flint and python-flint are being built with MSVC and that Flint is being built with the CMake build script rather than the autotools one.

The missing symbol `__flint_clz_tab` is not something that is used explicitly in python-flint anywhere but it is mentioned in the Flint headers that get included.

There are a bunch of `#ifdef` for this that are tricky to follow. The `__flint_clz_tab` is only actually defined here under `generic_files` which I guess is not always included:
https://github.com/flintlib/flint/blob/042e3782d6b915edbca82130471ab123d56f76f0/src/generic_files/clz_tab.c#L31
The `#ifdef` for this in the headers are here:
https://github.com/flintlib/flint/blob/042e3782d6b915edbca82130471ab123d56f76f0/src/longlong.h#L66-L69
So my guess is that including the header somehow hits that path but the build has not included the `generic_files`.

It might be that this is a problem with Flint's CMake build that it somehow builds in a way that is inconsistent with what is subsequently expected from the generated headers.

CC @isuruf

**Comment by oscarbenjamin** [comment]
Great. Thanks both!

**Pull request merged**
